// <auto-generated />
using EF10_NewFeaturesDbLibrary;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF10_NewFeaturesDbLibrary.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20250831072325_default-columns-renamed")]
    partial class defaultcolumnsrenamed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.7.25380.108")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF10_NewFeaturesModels.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Movie",
                            Description = "Film or motion picture",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Book",
                            Description = "Printed or written literary work",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Game",
                            Description = "Interactive entertainment",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Toy/Collectable",
                            Description = "Physical toy or collectible",
                            IsActive = true,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("EF10_NewFeaturesModels.Contributor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContributorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ContributorName")
                        .IsUnique();

                    b.ToTable("Contributors");
                });

            modelBuilder.Entity("EF10_NewFeaturesModels.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("GenreName")
                        .IsUnique();

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GenreName = "Science Fiction",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            GenreName = "Fantasy",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            GenreName = "Adventure",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            GenreName = "Classic",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            GenreName = "Thriller",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            GenreName = "Horror",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 7,
                            GenreName = "Mystery",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 8,
                            GenreName = "Action",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 9,
                            GenreName = "Drama",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 10,
                            GenreName = "Superhero",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 11,
                            GenreName = "Collectible",
                            IsActive = true,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("EF10_NewFeaturesModels.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true, "DF_ItemIsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnSale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_ItemIsOnSale");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TenantId");

                    b.HasIndex("ItemName", "CategoryId", "TenantId")
                        .IsUnique();

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "The original Star Wars movie.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "Star Wars: A New Hope",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Classic fantasy novel by J.R.R. Tolkien.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "The Lord of the Rings: The Fellowship of the Ring",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "Popular online multiplayer tank game.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "World of Tanks",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Description = "Collectible Hallmark ornament.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "Star Trek™: U.S.S. Enterprise: NCC-1701 Ornament",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Christopher Nolan's Batman movie.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "Batman Begins",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Film adaptation of Frank Herbert's novel.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "Dune (2021)",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "First Harry Potter movie.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "Harry Potter and the Sorcerer's Stone",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "Horror film based on Stephen King's book.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "The Shining",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Description = "Mind-bending thriller by Christopher Nolan.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "Inception",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Description = "Sequel to Batman Begins.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "The Dark Knight",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Description = "Adaptation of Agatha Christie's mystery.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "Murder on the Orient Express (2017)",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            Description = "Sci-fi epic by Christopher Nolan.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "Interstellar",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            Description = "Groundbreaking action sci-fi film.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "The Matrix",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            Description = "Adventure film with dinosaurs.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "Jurassic Park",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            Description = "Classic crime drama.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "The Godfather",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            Description = "Quentin Tarantino's nonlinear crime film.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "Pulp Fiction",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            Description = "Psychological thriller.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "Fight Club",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            Description = "Heartwarming drama.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "Forrest Gump",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            Description = "Prison drama based on Stephen King story.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "The Shawshank Redemption",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            Description = "Sequel to A New Hope.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "The Empire Strikes Back",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            Description = "Sci-fi novel by Frank Herbert (crossover with movie).",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "Dune",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            Description = "First Harry Potter book (crossover with movie).",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "Harry Potter and the Sorcerer's Stone",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            Description = "Horror novel by Stephen King (crossover with movie).",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "The Shining",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 2,
                            Description = "Mystery novel by Agatha Christie (crossover with movie).",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "Murder on the Orient Express",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 2,
                            Description = "Horror novel by Stephen King.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "It",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 2,
                            Description = "Fantasy prequel to Lord of the Rings.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "The Hobbit",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 2,
                            Description = "Dystopian classic by George Orwell.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "1984",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 2,
                            Description = "Classic novel by Harper Lee.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "To Kill a Mockingbird",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 2,
                            Description = "F. Scott Fitzgerald's jazz age novel.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "The Great Gatsby",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 2,
                            Description = "Jane Austen's romantic classic.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "Pride and Prejudice",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 2,
                            Description = "J.D. Salinger's coming-of-age story.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "The Catcher in the Rye",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 2,
                            Description = "Aldous Huxley's dystopian vision.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "Brave New World",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 2,
                            Description = "Dan Brown's thriller.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "The Da Vinci Code",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 2,
                            Description = "Gillian Flynn's psychological thriller.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "Gone Girl",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 2,
                            Description = "Suzanne Collins' dystopian adventure.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "The Hunger Games",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 3,
                            Description = "MMORPG by Blizzard.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "World of Warcraft",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 3,
                            Description = "Open-world action game by Rockstar.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "Grand Theft Auto V",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 3,
                            Description = "Adventure game by Nintendo.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "The Legend of Zelda: Breath of the Wild",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 3,
                            Description = "Sandbox building game.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "Minecraft",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 3,
                            Description = "Battle royale shooter.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "Fortnite",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 3,
                            Description = "RPG based on Andrzej Sapkowski's books.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "The Witcher 3: Wild Hunt",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 3,
                            Description = "Team-based shooter by Blizzard.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "Overwatch",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 3,
                            Description = "Sci-fi RPG by CD Projekt Red.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "Cyberpunk 2077",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 3,
                            Description = "Historical action RPG.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "Assassin's Creed Valhalla",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 3,
                            Description = "Platformer by Nintendo.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "Super Mario Odyssey",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 4,
                            Description = "Collectible vinyl figure of Batman.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "Funko Pop! Batman",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 4,
                            Description = "Collectible wand from the series.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "Harry Potter Wand Replica",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 4,
                            Description = "Replica lightsaber.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "Star Wars Lightsaber Toy",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 4,
                            Description = "One Ring collectible.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "Lord of the Rings Ring Replica",
                            TenantId = 1
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 4,
                            Description = "Collectible figure from Dune.",
                            IsActive = true,
                            IsDeleted = false,
                            IsOnSale = false,
                            ItemName = "Dune Sandworm Figure",
                            TenantId = 1
                        });
                });

            modelBuilder.Entity("EF10_NewFeaturesModels.ItemContributor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContributorId")
                        .HasColumnType("int");

                    b.Property<int?>("ContributorType")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContributorId");

                    b.HasIndex("ItemId", "ContributorId")
                        .IsUnique();

                    b.ToTable("ItemContributors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContributorId = 1,
                            ContributorType = 6,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 1
                        },
                        new
                        {
                            Id = 2,
                            ContributorId = 2,
                            ContributorType = 6,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 1
                        },
                        new
                        {
                            Id = 3,
                            ContributorId = 3,
                            ContributorType = 4,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 1
                        },
                        new
                        {
                            Id = 4,
                            ContributorId = 4,
                            ContributorType = 7,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 1
                        },
                        new
                        {
                            Id = 5,
                            ContributorId = 5,
                            ContributorType = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 2
                        },
                        new
                        {
                            Id = 6,
                            ContributorId = 6,
                            ContributorType = 9,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 3
                        },
                        new
                        {
                            Id = 7,
                            ContributorId = 7,
                            ContributorType = 10,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 4
                        },
                        new
                        {
                            Id = 8,
                            ContributorId = 8,
                            ContributorType = 6,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 5
                        },
                        new
                        {
                            Id = 9,
                            ContributorId = 9,
                            ContributorType = 6,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 5
                        },
                        new
                        {
                            Id = 10,
                            ContributorId = 10,
                            ContributorType = 4,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 5
                        },
                        new
                        {
                            Id = 11,
                            ContributorId = 11,
                            ContributorType = 7,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 5
                        },
                        new
                        {
                            Id = 12,
                            ContributorId = 12,
                            ContributorType = 7,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 5
                        },
                        new
                        {
                            Id = 13,
                            ContributorId = 14,
                            ContributorType = 4,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 6
                        },
                        new
                        {
                            Id = 14,
                            ContributorId = 15,
                            ContributorType = 6,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 6
                        },
                        new
                        {
                            Id = 15,
                            ContributorId = 16,
                            ContributorType = 6,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 6
                        },
                        new
                        {
                            Id = 16,
                            ContributorId = 11,
                            ContributorType = 7,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 6
                        },
                        new
                        {
                            Id = 17,
                            ContributorId = 19,
                            ContributorType = 4,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 7
                        },
                        new
                        {
                            Id = 18,
                            ContributorId = 18,
                            ContributorType = 6,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 7
                        },
                        new
                        {
                            Id = 19,
                            ContributorId = 22,
                            ContributorType = 4,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 8
                        },
                        new
                        {
                            Id = 20,
                            ContributorId = 23,
                            ContributorType = 6,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 8
                        },
                        new
                        {
                            Id = 21,
                            ContributorId = 10,
                            ContributorType = 4,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 9
                        },
                        new
                        {
                            Id = 22,
                            ContributorId = 11,
                            ContributorType = 7,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 9
                        },
                        new
                        {
                            Id = 23,
                            ContributorId = 10,
                            ContributorType = 4,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 10
                        },
                        new
                        {
                            Id = 24,
                            ContributorId = 8,
                            ContributorType = 6,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 10
                        },
                        new
                        {
                            Id = 25,
                            ContributorId = 11,
                            ContributorType = 7,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 10
                        },
                        new
                        {
                            Id = 26,
                            ContributorId = 27,
                            ContributorType = 4,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 11
                        },
                        new
                        {
                            Id = 27,
                            ContributorId = 10,
                            ContributorType = 4,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 12
                        },
                        new
                        {
                            Id = 28,
                            ContributorId = 11,
                            ContributorType = 7,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 12
                        },
                        new
                        {
                            Id = 29,
                            ContributorId = 3,
                            ContributorType = 4,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 13
                        },
                        new
                        {
                            Id = 30,
                            ContributorId = 4,
                            ContributorType = 7,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 14
                        },
                        new
                        {
                            Id = 31,
                            ContributorId = 10,
                            ContributorType = 4,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 15
                        },
                        new
                        {
                            Id = 32,
                            ContributorId = 22,
                            ContributorType = 4,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 16
                        },
                        new
                        {
                            Id = 33,
                            ContributorId = 10,
                            ContributorType = 4,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 17
                        },
                        new
                        {
                            Id = 34,
                            ContributorId = 11,
                            ContributorType = 7,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 18
                        },
                        new
                        {
                            Id = 35,
                            ContributorId = 21,
                            ContributorType = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 19
                        },
                        new
                        {
                            Id = 36,
                            ContributorId = 1,
                            ContributorType = 6,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 20
                        },
                        new
                        {
                            Id = 37,
                            ContributorId = 4,
                            ContributorType = 7,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 20
                        },
                        new
                        {
                            Id = 38,
                            ContributorId = 13,
                            ContributorType = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 21
                        },
                        new
                        {
                            Id = 39,
                            ContributorId = 17,
                            ContributorType = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 22
                        },
                        new
                        {
                            Id = 40,
                            ContributorId = 21,
                            ContributorType = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 23
                        },
                        new
                        {
                            Id = 41,
                            ContributorId = 26,
                            ContributorType = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 24
                        },
                        new
                        {
                            Id = 42,
                            ContributorId = 21,
                            ContributorType = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 25
                        },
                        new
                        {
                            Id = 43,
                            ContributorId = 5,
                            ContributorType = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 26
                        },
                        new
                        {
                            Id = 44,
                            ContributorId = 13,
                            ContributorType = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 27
                        },
                        new
                        {
                            Id = 45,
                            ContributorId = 26,
                            ContributorType = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 28
                        },
                        new
                        {
                            Id = 46,
                            ContributorId = 5,
                            ContributorType = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 29
                        },
                        new
                        {
                            Id = 47,
                            ContributorId = 17,
                            ContributorType = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 30
                        },
                        new
                        {
                            Id = 48,
                            ContributorId = 21,
                            ContributorType = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 31
                        },
                        new
                        {
                            Id = 49,
                            ContributorId = 13,
                            ContributorType = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 32
                        },
                        new
                        {
                            Id = 50,
                            ContributorId = 26,
                            ContributorType = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 33
                        },
                        new
                        {
                            Id = 51,
                            ContributorId = 21,
                            ContributorType = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 34
                        },
                        new
                        {
                            Id = 52,
                            ContributorId = 17,
                            ContributorType = 0,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 35
                        },
                        new
                        {
                            Id = 53,
                            ContributorId = 20,
                            ContributorType = 12,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 36
                        },
                        new
                        {
                            Id = 54,
                            ContributorId = 25,
                            ContributorType = 12,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 37
                        },
                        new
                        {
                            Id = 55,
                            ContributorId = 20,
                            ContributorType = 9,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 38
                        },
                        new
                        {
                            Id = 56,
                            ContributorId = 6,
                            ContributorType = 12,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 39
                        },
                        new
                        {
                            Id = 57,
                            ContributorId = 25,
                            ContributorType = 12,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 40
                        },
                        new
                        {
                            Id = 58,
                            ContributorId = 20,
                            ContributorType = 12,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 41
                        },
                        new
                        {
                            Id = 59,
                            ContributorId = 20,
                            ContributorType = 12,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 42
                        },
                        new
                        {
                            Id = 60,
                            ContributorId = 25,
                            ContributorType = 12,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 43
                        },
                        new
                        {
                            Id = 61,
                            ContributorId = 6,
                            ContributorType = 9,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 44
                        },
                        new
                        {
                            Id = 62,
                            ContributorId = 20,
                            ContributorType = 12,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 45
                        },
                        new
                        {
                            Id = 63,
                            ContributorId = 24,
                            ContributorType = 10,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 46
                        },
                        new
                        {
                            Id = 64,
                            ContributorId = 7,
                            ContributorType = 10,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 47
                        },
                        new
                        {
                            Id = 65,
                            ContributorId = 24,
                            ContributorType = 10,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 48
                        },
                        new
                        {
                            Id = 66,
                            ContributorId = 7,
                            ContributorType = 10,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 49
                        },
                        new
                        {
                            Id = 67,
                            ContributorId = 24,
                            ContributorType = 10,
                            IsActive = true,
                            IsDeleted = false,
                            ItemId = 50
                        });
                });

            modelBuilder.Entity("EF10_NewFeaturesModels.JunkToBulkDelete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("JunkToBulkDeletes");
                });

            modelBuilder.Entity("EF10_NewFeaturesModels.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("TenantName")
                        .IsUnique();

                    b.ToTable("Tenant");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            IsDeleted = false,
                            TenantName = "Default Tenant"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            IsDeleted = false,
                            TenantName = "Another Tenant"
                        });
                });

            modelBuilder.Entity("ItemGenres", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("ItemId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("ItemGenres");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            GenreId = 1
                        },
                        new
                        {
                            ItemId = 1,
                            GenreId = 8
                        },
                        new
                        {
                            ItemId = 2,
                            GenreId = 2
                        },
                        new
                        {
                            ItemId = 2,
                            GenreId = 3
                        },
                        new
                        {
                            ItemId = 2,
                            GenreId = 4
                        },
                        new
                        {
                            ItemId = 3,
                            GenreId = 8
                        },
                        new
                        {
                            ItemId = 4,
                            GenreId = 11
                        },
                        new
                        {
                            ItemId = 5,
                            GenreId = 8
                        },
                        new
                        {
                            ItemId = 5,
                            GenreId = 9
                        },
                        new
                        {
                            ItemId = 5,
                            GenreId = 10
                        },
                        new
                        {
                            ItemId = 6,
                            GenreId = 1
                        },
                        new
                        {
                            ItemId = 6,
                            GenreId = 3
                        },
                        new
                        {
                            ItemId = 7,
                            GenreId = 2
                        },
                        new
                        {
                            ItemId = 7,
                            GenreId = 3
                        },
                        new
                        {
                            ItemId = 8,
                            GenreId = 6
                        },
                        new
                        {
                            ItemId = 8,
                            GenreId = 5
                        },
                        new
                        {
                            ItemId = 9,
                            GenreId = 5
                        },
                        new
                        {
                            ItemId = 9,
                            GenreId = 1
                        },
                        new
                        {
                            ItemId = 10,
                            GenreId = 8
                        },
                        new
                        {
                            ItemId = 10,
                            GenreId = 10
                        },
                        new
                        {
                            ItemId = 10,
                            GenreId = 9
                        },
                        new
                        {
                            ItemId = 11,
                            GenreId = 7
                        },
                        new
                        {
                            ItemId = 11,
                            GenreId = 5
                        },
                        new
                        {
                            ItemId = 12,
                            GenreId = 1
                        },
                        new
                        {
                            ItemId = 12,
                            GenreId = 9
                        },
                        new
                        {
                            ItemId = 13,
                            GenreId = 1
                        },
                        new
                        {
                            ItemId = 13,
                            GenreId = 8
                        },
                        new
                        {
                            ItemId = 14,
                            GenreId = 3
                        },
                        new
                        {
                            ItemId = 14,
                            GenreId = 1
                        },
                        new
                        {
                            ItemId = 15,
                            GenreId = 9
                        },
                        new
                        {
                            ItemId = 15,
                            GenreId = 4
                        },
                        new
                        {
                            ItemId = 16,
                            GenreId = 5
                        },
                        new
                        {
                            ItemId = 16,
                            GenreId = 9
                        },
                        new
                        {
                            ItemId = 17,
                            GenreId = 5
                        },
                        new
                        {
                            ItemId = 17,
                            GenreId = 9
                        },
                        new
                        {
                            ItemId = 18,
                            GenreId = 9
                        },
                        new
                        {
                            ItemId = 18,
                            GenreId = 4
                        },
                        new
                        {
                            ItemId = 19,
                            GenreId = 9
                        },
                        new
                        {
                            ItemId = 19,
                            GenreId = 4
                        },
                        new
                        {
                            ItemId = 20,
                            GenreId = 1
                        },
                        new
                        {
                            ItemId = 20,
                            GenreId = 8
                        },
                        new
                        {
                            ItemId = 21,
                            GenreId = 1
                        },
                        new
                        {
                            ItemId = 21,
                            GenreId = 3
                        },
                        new
                        {
                            ItemId = 21,
                            GenreId = 4
                        },
                        new
                        {
                            ItemId = 22,
                            GenreId = 2
                        },
                        new
                        {
                            ItemId = 22,
                            GenreId = 3
                        },
                        new
                        {
                            ItemId = 23,
                            GenreId = 6
                        },
                        new
                        {
                            ItemId = 23,
                            GenreId = 5
                        },
                        new
                        {
                            ItemId = 24,
                            GenreId = 7
                        },
                        new
                        {
                            ItemId = 24,
                            GenreId = 4
                        },
                        new
                        {
                            ItemId = 25,
                            GenreId = 6
                        },
                        new
                        {
                            ItemId = 26,
                            GenreId = 2
                        },
                        new
                        {
                            ItemId = 26,
                            GenreId = 3
                        },
                        new
                        {
                            ItemId = 27,
                            GenreId = 1
                        },
                        new
                        {
                            ItemId = 27,
                            GenreId = 4
                        },
                        new
                        {
                            ItemId = 28,
                            GenreId = 9
                        },
                        new
                        {
                            ItemId = 28,
                            GenreId = 4
                        },
                        new
                        {
                            ItemId = 29,
                            GenreId = 9
                        },
                        new
                        {
                            ItemId = 29,
                            GenreId = 4
                        },
                        new
                        {
                            ItemId = 30,
                            GenreId = 9
                        },
                        new
                        {
                            ItemId = 30,
                            GenreId = 4
                        },
                        new
                        {
                            ItemId = 31,
                            GenreId = 9
                        },
                        new
                        {
                            ItemId = 31,
                            GenreId = 4
                        },
                        new
                        {
                            ItemId = 32,
                            GenreId = 1
                        },
                        new
                        {
                            ItemId = 32,
                            GenreId = 4
                        },
                        new
                        {
                            ItemId = 33,
                            GenreId = 5
                        },
                        new
                        {
                            ItemId = 33,
                            GenreId = 7
                        },
                        new
                        {
                            ItemId = 34,
                            GenreId = 5
                        },
                        new
                        {
                            ItemId = 34,
                            GenreId = 7
                        },
                        new
                        {
                            ItemId = 35,
                            GenreId = 3
                        },
                        new
                        {
                            ItemId = 35,
                            GenreId = 1
                        },
                        new
                        {
                            ItemId = 36,
                            GenreId = 2
                        },
                        new
                        {
                            ItemId = 36,
                            GenreId = 3
                        },
                        new
                        {
                            ItemId = 37,
                            GenreId = 8
                        },
                        new
                        {
                            ItemId = 37,
                            GenreId = 3
                        },
                        new
                        {
                            ItemId = 38,
                            GenreId = 3
                        },
                        new
                        {
                            ItemId = 38,
                            GenreId = 2
                        },
                        new
                        {
                            ItemId = 39,
                            GenreId = 3
                        },
                        new
                        {
                            ItemId = 40,
                            GenreId = 8
                        },
                        new
                        {
                            ItemId = 41,
                            GenreId = 2
                        },
                        new
                        {
                            ItemId = 41,
                            GenreId = 3
                        },
                        new
                        {
                            ItemId = 42,
                            GenreId = 8
                        },
                        new
                        {
                            ItemId = 42,
                            GenreId = 1
                        },
                        new
                        {
                            ItemId = 43,
                            GenreId = 1
                        },
                        new
                        {
                            ItemId = 43,
                            GenreId = 8
                        },
                        new
                        {
                            ItemId = 44,
                            GenreId = 8
                        },
                        new
                        {
                            ItemId = 44,
                            GenreId = 3
                        },
                        new
                        {
                            ItemId = 45,
                            GenreId = 3
                        },
                        new
                        {
                            ItemId = 46,
                            GenreId = 11
                        },
                        new
                        {
                            ItemId = 46,
                            GenreId = 10
                        },
                        new
                        {
                            ItemId = 47,
                            GenreId = 11
                        },
                        new
                        {
                            ItemId = 47,
                            GenreId = 2
                        },
                        new
                        {
                            ItemId = 48,
                            GenreId = 11
                        },
                        new
                        {
                            ItemId = 48,
                            GenreId = 1
                        },
                        new
                        {
                            ItemId = 49,
                            GenreId = 11
                        },
                        new
                        {
                            ItemId = 49,
                            GenreId = 2
                        },
                        new
                        {
                            ItemId = 50,
                            GenreId = 11
                        },
                        new
                        {
                            ItemId = 50,
                            GenreId = 1
                        });
                });

            modelBuilder.Entity("EF10_NewFeaturesModels.Contributor", b =>
                {
                    b.OwnsOne("EF10_NewFeaturesModels.Address", "Address", b1 =>
                        {
                            b1.Property<int>("ContributorId")
                                .HasColumnType("int");

                            b1.Property<string>("AddressLine1")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("AddressLine2")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("City")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("POBox")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("State")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ContributorId");

                            b1.ToTable("Contributors");

                            b1.ToJson("Address");

                            b1.WithOwner()
                                .HasForeignKey("ContributorId");
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("EF10_NewFeaturesModels.Item", b =>
                {
                    b.HasOne("EF10_NewFeaturesModels.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF10_NewFeaturesModels.Tenant", "Tenant")
                        .WithMany("Items")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EF10_NewFeaturesModels.ItemContributor", b =>
                {
                    b.HasOne("EF10_NewFeaturesModels.Contributor", "Contributor")
                        .WithMany("ContributorItems")
                        .HasForeignKey("ContributorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF10_NewFeaturesModels.Item", "Item")
                        .WithMany("ItemContributors")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contributor");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("ItemGenres", b =>
                {
                    b.HasOne("EF10_NewFeaturesModels.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF10_NewFeaturesModels.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EF10_NewFeaturesModels.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("EF10_NewFeaturesModels.Contributor", b =>
                {
                    b.Navigation("ContributorItems");
                });

            modelBuilder.Entity("EF10_NewFeaturesModels.Item", b =>
                {
                    b.Navigation("ItemContributors");
                });

            modelBuilder.Entity("EF10_NewFeaturesModels.Tenant", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
